name: Android Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Assets
        run: echo "Web dosyaları zaten hazır." # Bizim projemiz statik olduğu için build adımı gerekmiyor.

      - name: Setup Capacitor
        run: |
          npx cap init "Hm Hesabi" "com.sirketim.hmhesabi" --web-dir "."
          npx cap add android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hm-hesabi-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk